window.womenInQuantumData = [
  {
    id: "anna-beata-hedegaard",
    group: "women-in-quantum",
    name: "Anna Beata Kalisz Hedegaard",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 1",
    focus: "Fearless curiosity and human-centered quantum leadership",
    quote: "When I was a child, I was fearless and I want to go back there.",
    linkedinUrl: "https://www.linkedin.com/in/annabeata/",
    imageSrc: "Images/annabeatahedegaard.jfif",
    imageAlt: "Anna Beata Kalisz Hedegaard",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/3e69a84a-bd41-48e2-a449-e18941c42557/transcript.srt",
    infographicSrc: "Infograhics/S1E1.png",
    infographicAlt: "Infographic from Anna Beata Kalisz Hedegaard's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "anna-white",
    group: "impact-quantum",
    name: "Anna White",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 1, Episode 2",
    focus: "Quantum networking and security-first infrastructure",
    quote: "Add a pull quote from Anna White's episode.",
    linkedinUrl: "https://www.linkedin.com/in/anna-white-a22127320/",
    imageSrc: "Images/Anna White.jfif",
    imageAlt: "Anna White",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/d10b5203-08ff-4367-a903-b4bf7ffb826b/transcript.srt",
    infographicSrc: "",
    infographicAlt: "Infographic from Anna White's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "benita-zazueta",
    group: "impact-quantum",
    name: "Benita Zazueta",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 4, Episode 4",
    focus: "Helping governments and enterprises identify vulnerabilities and build cyber resilience for the quantum era",
    quote: "It's doable, but we have to start now.",
    linkedinUrl: "https://www.linkedin.com/in/benita-zazueta-mba-a9422112/",
    imageSrc: "Images/benita-zazueta.jfif",
    imageAlt: "Benita Zazueta",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/fa39bf74-7d62-44b7-b30e-6fba751a56df/transcript.srt",
    infographicSrc: "Infograhics/S1E2.png",
    infographicAlt: "Infographic from Benita Zazueta's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "bruna-shinohara",
    group: "women-in-quantum",
    name: "Bruna Shinohara",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 3",
    focus: "Accessible pathways into quantum beyond a physics background",
    quote: "Add a pull quote from Bruna Shinohara's episode.",
    linkedinUrl: "https://www.linkedin.com/in/bruna-shinohara-de-mendonca/",
    imageSrc: "Images/brunoshinohara.jfif",
    imageAlt: "Bruna Shinohara",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/4975c0b0-a0f5-473f-b947-d6a55a2914c0/transcript.srt",
    infographicSrc: "Infograhics/S1E3.png",
    infographicAlt: "Infographic from Bruna Shinohara's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "devika-mehra",
    group: "women-in-quantum",
    name: "Devika Mehra",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 2",
    focus: "Confidence, resilience, and leadership in deep tech",
    quote: "We have an opportunity here to really build these security first principles into the quantum Internet as it evolves.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/devikamehar.jfif",
    imageAlt: "Devika Mehra",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/99fa97c0-bcb0-4c58-b854-ac1c6c4ded39/transcript.srt",
    infographicSrc: "Infograhics/Gemini_Generated_Image_jrcchdjrcchdjrcc.png",
    infographicAlt: "Infographic from Devika Mehra's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: ""
  },
  {
    id: "harshitta-gandhi",
    group: "women-in-quantum",
    name: "Harshitta Gandhi",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 3",
    focus: "Career pivots, curiosity, and taking chances in deep tech",
    quote: "Add a pull quote from Harshitta Gandhi's episode.",
    linkedinUrl: "https://www.linkedin.com/in/harshitta-gandhi/",
    imageSrc: "Images/Harshitta Gandhi.jfif",
    imageAlt: "Harshitta Gandhi",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/0478646f-0ddf-4b6d-b8e5-374b5b71f8fd/transcript.srt",
    infographicSrc: "",
    infographicAlt: "Infographic from Harshitta Gandhi's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "helena-bahrami",
    group: "impact-quantum",
    name: "Helena Bahrami",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 4, Episode 13",
    focus: "Bridging AI, quantum computing, and neuroscience to tackle neurodegenerative disease",
    quote: "If it is your passion, stick to that.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/Helena Bahrami.jfif",
    imageAlt: "Helena Bahrami",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/e86ea6cf-069d-4a65-8f8f-fd828a42f242/transcript.srt",
    infographicSrc: "Infograhics/HelanaBahrami.png",
    infographicAlt: "Infographic from Helena Bahrami's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: ""
  },
  {
    id: "jennifer-prendki",
    group: "women-in-quantum",
    name: "Jennifer Prendki",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 5",
    focus: "Quantum networking and security-first design",
    quote: "Confidence has to take the shape of, 'I do what I need to do and I ignore the noise.'",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/jenniferprendki.jfif",
    imageAlt: "Jennifer Prendki",
    clipSrc: "YT shorts/DeepMind PRIORITIZED Gemini Over View_ The Secret Behind Success!.mp4",
    clipPoster: "Images/jenniferprendki.jfif",
    clipLabel: "YouTube clip",
    clipExternalUrl: "",
    transcriptUrl: "https://www.showdog.studio/api/transcripts/9fa4679734319764a97ade42c814338f",
    infographicSrc: "Infograhics/Gemini_Generated_Image_z8dd49z8dd49z8dd.png",
    infographicAlt: "Infographic from Jennifer Prendki's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: "https://artwork.captivate.fm/d0a9d634-c01b-453e-9aa3-dd215f4b2c11/wiqcs1e5.jpg"
  },
  {
    id: "katanya-kuntz",
    group: "impact-quantum",
    name: "Katanya Kuntz",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 1, Episode 8",
    focus: "Bridging business and engineering to navigate multidisciplinary quantum work",
    quote: "Add a pull quote from Katanya Kuntz's episode.",
    linkedinUrl: "https://www.linkedin.com/in/katanya-b-kuntz/",
    imageSrc: "Images/katanyakuntz.jfif",
    imageAlt: "Katanya Kuntz",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Katanya Kuntz's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "marie-eve-boulonger",
    group: "women-in-quantum",
    name: "Marie-Eve Boulanger",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 7",
    focus: "Add episode focus",
    quote: "Quantum networking gives us a chance to build security into the foundation, instead of bolting it on later.",
    linkedinUrl: "https://www.linkedin.com/in/marieeveboulanger/",
    imageSrc: "Images/marie-eveboulonger.jfif",
    imageAlt: "Marie-Eve Boulanger",
    clipSrc: "YT shorts/Marie-Eve Boulanger YT clip.mp4",
    clipPoster: "Images/marie-eveboulonger.jfif",
    clipLabel: "YouTube clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "Infograhics/Gemini_Generated_Image_a8kx5va8kx5va8kx.png",
    infographicAlt: "Infographic from Marie-Eve Boulanger's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: "https://artwork.captivate.fm/0289c70c-c1c0-46cb-9795-1bc7034cc1e2/wiqcs1e8.jpg"
  },
  {
    id: "natasa-nadoveza",
    group: "impact-quantum",
    name: "Natasa Nadoveza",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 3, Episode 36",
    focus: "Bridging computational chemistry and quantum simulation to study molecules at their most fundamental level",
    quote: "One shouldn't be scared of not knowing things. It's completely normal.",
    linkedinUrl: "https://www.linkedin.com/in/natasanadoveza/",
    imageSrc: "Images/Natasa Nadoveza.jfif",
    imageAlt: "Natasa Nadoveza",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/b34bd569-5e9e-4862-81c3-0c40f1e84925/transcript.srt",
    infographicSrc: "",
    infographicAlt: "Infographic from Natasa Nadoveza's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "klem-jankiewicz",
    group: "impact-quantum",
    name: "Klem Jankiewicz",
    role: "Guest from Impact Quantum",
    company: "Add company",
    episode: "Season 4, Episode 8",
    focus: "Bringing industrial design thinking into quantum computing to make complex systems usable",
    quote: "There's like no roadmap, and that's really fascinating from a designer's perspective because we can actually design things for the first time.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/KlemJankiewicz.jfif",
    imageAlt: "Klem Jankiewicz",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/49b6a6d0-5c99-4629-aae5-dcd93accf70e/transcript.srt",
    infographicSrc: "",
    infographicAlt: "Infographic from Klem Jankiewicz's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "noelle-ibrahim",
    group: "women-in-quantum",
    name: "Noelle Ibrahim",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 4",
    focus: "Add episode focus",
    quote: "Add a pull quote from Noelle Ibrahim's episode.",
    linkedinUrl: "https://www.linkedin.com/in/noelleibrahimphd/",
    imageSrc: "Images/noelleibrahim.jfif",
    imageAlt: "Noelle Ibrahim",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Noelle Ibrahim's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "olga-mamlyga",
    group: "women-in-quantum",
    name: "Olga Mamlyga",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 6",
    focus: "Add episode focus",
    quote: "Add a pull quote from Olga Mamlyga's episode.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/olga.jfif",
    imageAlt: "Olga Mamlyga",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Olga Mamlyga's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "petra-soderling",
    group: "women-in-quantum",
    name: "Petra Soderling",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 6",
    focus: "Career pivots, curiosity, and taking chances in deep tech",
    quote: "People think that you need to have a PhD in physics in order to do anything in the industry. I have a business degree and I've done pretty well.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/petrasoderling.jfif",
    imageAlt: "Petra Soderling",
    clipSrc: "YT shorts/Quantum Biology_ The Next Frontier of Science.mp4",
    clipPoster: "Images/petrasoderling.jfif",
    clipLabel: "YouTube clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/0478646f-0ddf-4b6d-b8e5-374b5b71f8fd/transcript.srt",
    infographicSrc: "Infograhics/S1E6.png",
    infographicAlt: "Infographic from Petra Soderling's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: "https://artwork.captivate.fm/9ea09027-fde4-4c96-b8a2-387a15a2ebbb/wiqcs1e7.jpg"
  },
  {
    id: "rachel-noek",
    group: "women-in-quantum",
    name: "Rachel Noek",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 3",
    focus: "Add episode focus",
    quote: "Add a pull quote from Rachel Noek's episode.",
    linkedinUrl: "https://www.linkedin.com/in/rachel-noek-qc/",
    imageSrc: "Images/rachelnoek.jfif",
    imageAlt: "Rachel Noek",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Rachel Noek's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "sabine-mehr",
    group: "women-in-quantum",
    name: "Sabine Mehr",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 3",
    focus: "Bridging business and engineering to navigate multidisciplinary quantum work",
    quote: "Success for me would be to live exciting adventures during the day and still be home in time to share dinner with my daughter.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/sabinemehr.jfif",
    imageAlt: "Sabine Mehr",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/390b4cd2-6790-4488-b631-9803b41e5c73/transcript.srt",
    infographicSrc: "Infograhics/Gemini_Generated_Image_j5dnwqj5dnwqj5dn.png",
    infographicAlt: "Infographic from Sabine Mehr's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: ""
  },
  {
    id: "sahar-hejazi",
    group: "women-in-quantum",
    name: "Sahar Hejazi",
    role: "Guest from the show",
    company: "Add company",
    episode: "Add episode",
    focus: "Add episode focus",
    quote: "Add a pull quote from Sahar Hejazi's episode.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/Sahar Hejazi.jfif",
    imageAlt: "Sahar Hejazi",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Sahar Hejazi's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "sahar-ben-rached",
    group: "women-in-quantum",
    name: "Sahar Ben Rached",
    role: "Guest from the show",
    company: "Add company",
    episode: "Add episode",
    focus: "Add episode focus",
    quote: "Add a pull quote from Sahar Ben Rached's episode.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/SaharBenRached.jfif",
    imageAlt: "Sahar Ben Rached",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Sahar Ben Rached's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  },
  {
    id: "sara-metwalli",
    group: "women-in-quantum",
    name: "Sara Metwalli",
    role: "Guest from the show",
    company: "Add company",
    episode: "Season 1, Episode 4",
    focus: "Breaking into quantum from electrical engineering through curiosity, coding, and applications",
    quote: "Math is the language of the universe.",
    linkedinUrl: "https://www.linkedin.com/",
    imageSrc: "Images/sarametwalli.jfif",
    imageAlt: "Sara Metwalli",
    clipSrc: "",
    clipPoster: "",
    clipLabel: "Add MP4 clip",
    clipExternalUrl: "",
    transcriptUrl: "https://transcripts.captivate.fm/transcript/3b5462ed-db24-4f5e-8d98-aa0e33c32e1d/transcript.srt",
    infographicSrc: "Infograhics/Gemini_Generated_Image_lkwz9alkwz9alkwz.png",
    infographicAlt: "Infographic from Sara Metwalli's episode",
    infographicLabel: "Episode infographic",
    infographicUrl: "https://artwork.captivate.fm/0cf96f33-7321-4086-992c-f8571f079df3/wiqcs1e4.jpg"
  },
  {
    id: "sierra-clouse",
    group: "women-in-quantum",
    name: "Sierra Clouse",
    role: "Guest from the show",
    company: "Add company",
    episode: "Add episode",
    focus: "Add episode focus",
    quote: "I kind of just came from a background of people who would be willing to take a chance.",
    linkedinUrl: "https://www.linkedin.com/in/sierraclouse/",
    imageSrc: "Images/SierraClouse.jfif",
    imageAlt: "Sierra Clouse",
    clipSrc: "YT shorts/Blockchain_ Beyond Crypto, Cryptography is Key!.mp4",
    clipPoster: "Images/SierraClouse.jfif",
    clipLabel: "YouTube clip",
    clipExternalUrl: "",
    transcriptUrl: "",
    infographicSrc: "",
    infographicAlt: "Infographic from Sierra Clouse's episode",
    infographicLabel: "Add JPG or PNG infographic",
    infographicUrl: ""
  }
];
